language: ruby
rvm:
  - 2.6.3

# install will run bundle install by default (make sure Gemfile has dependencies)
#install: gem install bundler && bundle install

script: jekyll build && htmlproofer ./_site
#script: bundle exec jekyll build && htmlproofer ./_site
#script: bundle exec jekyll build

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build
 
#cache:
#  directories:
#  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false
