language: ruby
rvm:
  - 2.6.3

# install will run bundle install by default (make sure Gemfile has dependencies)
#install: gem install bundler && bundle install

script: bundle exec jekyll build && bundle exec htmlproofer ./_site --only-4xx --ignore_status_codes "400,401,403" --enforce_https false --ignore_urls "/LaPy,/LaPy/,/BrainPrint,/fsqc/,https://dx.doi.org/10.3174/ajnr.A4508,https://dx.doi.org/10.1212/WNL.0000000000000187"
#passing longer timeout for external url check:
#script: bundle exec jekyll build && bundle exec htmlproofer ./_site --typhoeus '{ "timeout":30 , "verbose":"true" }'

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors

cache:
  bundler: true # caching bundler gem packages will speed up build
  directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false
